Reset stopTraining at start of model training
tensorflow/tfjs-layers pull request #376
Opened 2018-11-18 00:40 UTC by dsanders11

#### Description

It's a bit unexpected that `stopTraining` stays set even when calling `fit` again. Running `fit` on a model that had `stopTraining` set currently leads to it running for a moment then exiting.

PR resets `stopTraining` at the start of each training run, I can't think of any reason why you'd want it to persist and stop new calls to `fit` immediately.

---
##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

2018-11-19 19:09 UTC, caisq requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/376)* status: 0 of 1 approvals obtained (waiting on @dsanders11)

___
*[src/engine/training_dataset.ts, line 281 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/376#-LRhMkb_BFCDgulgJywf:-LRhMkb_BFCDgulgJywg:b-gq4g5w) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/18542b2b307002f1de4b93fcfebf9815441dfc86/src/engine/training_dataset.ts#L281)):*
> ```
>  model.stopTraining_ = false;
> ```

Thanks, @dsanders11 ! This change makes sense and LGTM. 

But do you mind adding a unit test for each of these two changes? The test can live in training_test.ts and training_dataset_test.ts. You can follow the example of https://github.com/tensorflow/tfjs-layers/blob/master/src/engine/training_test.ts#L1199 to write the new tests.


<!-- Sent from Reviewable.io -->

2018-11-20 20:46 UTC, dsanders11 commented
While doing the unit tests I discovered this was actually already being done for `fitTensors` at [this line](https://github.com/tensorflow/tfjs-layers/blob/c785709a6eecb0515cc1e01853c2edacdac247dc/src/engine/training_tensors.ts#L308). It's only `fitDataset` that has the issue (which is where I noticed it to begin with).

I've also noticed a different bug which I opened #378 for, and that PR should be merged before I finish this one off.

2018-11-20 21:13 UTC, dsanders11 commented
This branch got all messed up after I tried to rebase after #378 was merged, so I force-pushed to clean it up.

Unit tests added, and now there's only small change in `fitDataset` which mirrors what's in `fitTensors`.

2018-11-20 21:20 UTC, dsanders11 commented
Just noticed the unit test in `training_dataset_test.ts` carried over a typo when I copied and pasted, so opened #379 to fix the typo in the original file. There was no test coverage of stopping training in `training_dataset_test.ts`, so I duplicated `StopAfterNBatches` from `training_test.ts`, but it might be preferable to make a `test_utils.ts` and put that and `StopAfterNEpochs` in there.

2018-11-21 03:29 UTC, caisq approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/376#-:-LRoJ9p619b0Wj7C7gNe:b-uwkowd)* status: 0 of 1 approvals obtained (waiting on @dsanders11)



<!-- Sent from Reviewable.io -->

2018-11-21 14:35 UTC, merged